<?php

namespace Container3c8EWVq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KFQQBqTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kFQQBqT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kFQQBqT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sandwich' => ['privates', '.errored..service_locator.kFQQBqT.App\\Entity\\Sandwichs', NULL, 'Cannot autowire service ".service_locator.kFQQBqT": it needs an instance of "App\\Entity\\Sandwichs" but this type has been excluded in "config/services.yaml".'],
        ], [
            'sandwich' => 'App\\Entity\\Sandwichs',
        ]);
    }
}
