<?php

namespace Container9bvnSfx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XVvLpJUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xVvLpJU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xVvLpJU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['privates', '.errored..service_locator.xVvLpJU.Doctrine\\ORM\\EntityManager', NULL, 'Cannot autowire service ".service_locator.xVvLpJU": it references class "Doctrine\\ORM\\EntityManager" but no such service exists. Try changing the type-hint to "Doctrine\\ORM\\EntityManagerInterface" instead.'],
            'jwt' => ['privates', 'App\\Service\\JWTService', 'getJWTServiceService', true],
            'mail' => ['privates', 'App\\Service\\SendMailService', 'getSendMailServiceService', true],
            'user' => ['privates', '.errored..service_locator.xVvLpJU.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.xVvLpJU": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => 'Doctrine\\ORM\\EntityManager',
            'jwt' => 'App\\Service\\JWTService',
            'mail' => 'App\\Service\\SendMailService',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
