<?php

namespace Container9bvnSfx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B0FbZ8jService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.b0FbZ8j' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.b0FbZ8j'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'burgersRepository' => ['privates', 'App\\Repository\\BurgersRepository', 'getBurgersRepositoryService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'user' => ['privates', '.errored..service_locator.b0FbZ8j.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.b0FbZ8j": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'burgersRepository' => 'App\\Repository\\BurgersRepository',
            'mailer' => '?',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
