<?php

namespace Container9bvnSfx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PKUahGaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PKUahGa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PKUahGa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'texmex' => ['privates', '.errored..service_locator.PKUahGa.App\\Entity\\Texmexs', NULL, 'Cannot autowire service ".service_locator.PKUahGa": it needs an instance of "App\\Entity\\Texmexs" but this type has been excluded in "config/services.yaml".'],
        ], [
            'texmex' => 'App\\Entity\\Texmexs',
        ]);
    }
}
