<?php

namespace Container6wxV9jr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IC38EgdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IC38Egd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IC38Egd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sandwichsRepository' => ['privates', 'App\\Repository\\SandwichsRepository', 'getSandwichsRepositoryService', true],
        ], [
            'sandwichsRepository' => 'App\\Repository\\SandwichsRepository',
        ]);
    }
}
