<?php

namespace Container6wxV9jr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_400NPhuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.400NPhu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.400NPhu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'UserRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'em' => ['privates', '.errored..service_locator.400NPhu.Doctrine\\ORM\\EntityManager', NULL, 'Cannot autowire service ".service_locator.400NPhu": it references class "Doctrine\\ORM\\EntityManager" but no such service exists. Try changing the type-hint to "Doctrine\\ORM\\EntityManagerInterface" instead.'],
            'jwt' => ['privates', 'App\\Service\\JWTService', 'getJWTServiceService', true],
            'mail' => ['privates', 'App\\Service\\SendMailService', 'getSendMailServiceService', true],
        ], [
            'UserRepository' => 'App\\Repository\\UserRepository',
            'em' => 'Doctrine\\ORM\\EntityManager',
            'jwt' => 'App\\Service\\JWTService',
            'mail' => 'App\\Service\\SendMailService',
        ]);
    }
}
