<?php

namespace Container6wxV9jr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTexmexs2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hwxRnby.App\Entity\Texmexs' shared service.
     *
     * @return \App\Entity\Texmexs
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.hwxRnby": it needs an instance of "App\\Entity\\Texmexs" but this type has been excluded in "config/services.yaml".');
    }
}
