<?php

namespace ContainerYxnQj7a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HwxRnbyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hwxRnby' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hwxRnby'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'texmex' => ['privates', '.errored..service_locator.hwxRnby.App\\Entity\\Texmexs', NULL, 'Cannot autowire service ".service_locator.hwxRnby": it needs an instance of "App\\Entity\\Texmexs" but this type has been excluded in "config/services.yaml".'],
            'texmexsRepository' => ['privates', 'App\\Repository\\TexmexsRepository', 'getTexmexsRepositoryService', true],
        ], [
            'texmex' => 'App\\Entity\\Texmexs',
            'texmexsRepository' => 'App\\Repository\\TexmexsRepository',
        ]);
    }
}
