<?php

namespace ContainerYxnQj7a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBurgers3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.u1lHVoe.App\Entity\Burgers' shared service.
     *
     * @return \App\Entity\Burgers
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.u1lHVoe": it needs an instance of "App\\Entity\\Burgers" but this type has been excluded in "config/services.yaml".');
    }
}
