<?php

namespace ContainerYxnQj7a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSandwichs2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.uT3_pqh.App\Entity\Sandwichs' shared service.
     *
     * @return \App\Entity\Sandwichs
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.uT3_pqh": it needs an instance of "App\\Entity\\Sandwichs" but this type has been excluded in "config/services.yaml".');
    }
}
