<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRuO9fpi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRuO9fpi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRuO9fpi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRuO9fpi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRuO9fpi\App_KernelDevDebugContainer([
    'container.build_hash' => 'RuO9fpi',
    'container.build_id' => '6f473a91',
    'container.build_time' => 1685539923,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRuO9fpi');
