<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVnuT6UZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVnuT6UZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVnuT6UZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVnuT6UZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVnuT6UZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'VnuT6UZ',
    'container.build_id' => 'c6747a12',
    'container.build_time' => 1681397502,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVnuT6UZ');
